wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "medseg-train-ppo-threshold"
ahus_model:
  type: "ahus_model_rope_mixed"
  weights_path: "/weights/rope_mixed/latest.pth"

device: "cpu"
total_frames: 1000
eval_every_n_batches: 100
eval_max_steps: 10
dataset:
  size_threshold: 2097152 # 128^3
  base_dir: "/data/3D_val_complete_small"
agent:
  type: "PPO"
  kwargs:
    lr: 0.00001
    max_grad_norm: 100
  save_path: "/weights/rl/ppo_threshold.pth"
