wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "medseg-train-attention-ppo-threshold"
ahus_model:
  device: "cuda"
  type: "ahus_model_rope_mixed"
  weights_path: "weights/rope_mixed_120_accum/model_latest.pth"
env:
  device: "cpu"
  interact_device: "cuda"
total_frames: 30000
eval_every_n_batches: 100
eval_max_steps: 10
size_threshold: 4194304 # 256*128*128
# size_threshold: 32768 # 32^3
dataset:
  train_dir: "data/CVPR-BiomedSegFM/3D_val_npz"
  val_dir: "data/CVPR-BiomedSegFM/3D_val_curated"
  # train_dir: "data/CVPR-BiomedSegFM/3D_val_single"
  # val_dir: "data/CVPR-BiomedSegFM/3D_val_single"
  gt_dir: "data/CVPR-BiomedSegFM/3D_val_gt/3D_val_gt_interactive"
# dataset
agent:
  kwargs:
    _device: "cuda"
    gamma: 1.0
    lmbda: 0.0
    clip_epsilon: 0.1
    entropy_bonus: true
    entropy_coef: 0.01 # default
    critic_coef: 1
    loss_critic_type: "smooth_l1"
    lr: 0.0001
    max_grad_norm: 1
    batch_size: 1
    sub_batch_size: 1
    num_epochs: 10
    replay_buffer_device: "cuda"
    prompt_embedding_dim: 128
    backbone_out_size: 32
  save_path: "weights/attention_ppo_threshold/agent"
