wandb:
  entity: "valterschutz-chalmers-university-of-technology"
  project: "medseg-train-attention-ddpg-threshold"
ahus_model:
  device: "cuda"
  type: "ahus_model_rope_mixed"
  weights_path: "weights/rope_mixed_120_accum/model_latest.pth"
env:
  device: "cpu"
total_frames: 1000
eval_every_n_batches: 20
eval_max_steps: 10
dataset:
  # size_threshold: 16777216 # 256^3
  # size_threshold: 2097152 # 128^3
  size_threshold: 4194304 # 256*128*128
  base_dir: "data/CVPR-BiomedSegFM/3D_val_combined_single"
agent:
  kwargs:
    _device: "cpu"
    gamma: 0.99
    loss_function: "l2"
    delay_actor: false
    delay_value: true
    separate_losses: false
    update_tau: 0.005
    lr: 0.001
    max_grad_norm: 10
    replay_buffer_size: 10
    sub_batch_size: 1
    num_samples: 10
    replay_buffer_alpha: 0.6
    replay_buffer_beta_init: 0.4
    replay_buffer_beta_end: 1.0
    replay_buffer_beta_annealing_num_batches: 1000
    init_random_frames: 10
    replay_buffer_device: "cpu"
    prompt_embedding_dim: 128
    backbone_out_size: 16
  save_path: "weights/attention_ddpg_threshold/agent"
